---
- name: Create group "docker"
  group:
    name: docker
    state: present
- name: Create the {{os_user}} user
  user: 
    name: "{{os_user}}"
    append: yes 
    state: present 
    createhome: yes 
    shell: /bin/bash
    group: docker
- name: Allow to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: "{{os_user}} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: Set up authorized keys for the {{os_user}} user
  authorized_key: 
    user: "{{os_user}}"
    key: "{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub
- name: Password based logins are disabled - only public key based logins are allowed.
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: '^#?AuthenticationMethods'
    line: 'AuthenticationMethods publickey'
  notify:
    - restart ssh
- lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify:
    - restart ssh
- lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: '^#?ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'
  notify:
    - restart ssh
- lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
  notify:
    - restart ssh
- lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: "AllowUsers {{os_user}}"
  notify:
    - restart ssh
- name: Delete root keys
  file: 
    path: /root/.ssh
    state: absent
- name: Disable SWAP 
  shell: swapoff -a
  become: true
- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'


