---
- name: Load module 'br_netfilter'
  modprobe:
    name: br_netfilter
    state: present
- name: Copy conf for 'net.bridge.bridge-nf-call-iptables'
  copy: 
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
  register: sysctl_config
- name: Reload parameters sysctl
  shell: sysctl -p --system
  when: sysctl_config.changed
