---
- name: Create group "docker"
  group:
    name: docker
    state: present
- name: Create the {{os_user}} user
  user: 
    name: "{{os_user}}"
    append: yes 
    state: present 
    createhome: yes 
    shell: /bin/bash
    group: docker
- name: Allow to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: "{{os_user}} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: Set up authorized keys for the {{os_user}} user
  authorized_key: 
    user: "{{os_user}}"
    key: "{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub
