---
- name: Update APT cache
  apt:
    update_cache: yes
- name: Update all packages to the latest version
  apt:
    upgrade: dist
- name: Remove useless packages from the cache
  apt:
    autoclean: yes
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
- name: Disable unattended-upgrades
  copy: 
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades